import os

GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL = os.getenv("GROQ_MODEL", "openai/gpt-oss-120b")
OLLAMA_HOST = os.getenv("OLLAMA_HOST", "host.docker.internal")
LLM_API_URL = f"http://{OLLAMA_HOST}:11434/api/chat"
LLM_MODEL = os.getenv("OLLAMA_MODEL", "gemma2:2b ")
OLLAMA_TIMEOUT_SEC = int(os.getenv("OLLAMA_TIMEOUT_SEC", "600"))
OLLAMA_NUM_PREDICT = int(os.getenv("OLLAMA_NUM_PREDICT", "256"))
OLLAMA_NUM_THREAD = int(os.getenv("OLLAMA_NUM_THREAD", "4"))
OLLAMA_NUM_CTX = int(os.getenv("OLLAMA_NUM_CTX", "2048"))
USE_GROQ = False
USE_JSON_OBJECT_MODE = os.getenv("USE_JSON_OBJECT_MODE", "").lower() in ("true", "1", "yes")
FLUSH_ON_STARTUP = os.getenv("FLUSH_ON_STARTUP", "false").lower() in ("true", "1", "yes")
KAFKA_TOPIC_PLAN = "aura-plan"
KAFKA_TOPIC_STATS = "aura-stats"
KAFKA_BOOTSTRAP_SERVERS = 'kafka:29092'
TTL_MAP = {"SHORT": 300, "MEDIUM": 900, "LONG": 1800}
PRIORITY_TTL_MULT = 3.0
EVICT_TTL_MULT = 0.1
TTL_MIN_SECONDS = 60
TTL_MAX_SECONDS = 3600
GLOBAL_TTL_FACTOR_MIN = 0.2
GLOBAL_TTL_FACTOR_MAX = 3.0

AURA_CACHE_LIMIT_BYTES = 1200 * 1024.0
LRU_CACHE_LIMIT_BYTES = 1200 * 1024
MEMORY_REFRESH_INTERVAL_SEC = 1.0
TTL_TIME_COMPRESSION = float(os.getenv("AURA_TTL_TIME_COMPRESSION", "1.0"))
TINYLFU_SKETCH_WIDTH = int(os.getenv("TINYLFU_SKETCH_WIDTH", "256"))
TINYLFU_SKETCH_DEPTH = int(os.getenv("TINYLFU_SKETCH_DEPTH", "4"))
TINYLFU_DOORKEEPER_SIZE = int(os.getenv("TINYLFU_DOORKEEPER_SIZE", "8192"))
TINYLFU_RESET_INTERVAL = int(os.getenv("TINYLFU_RESET_INTERVAL", "100000"))
TINYLFU_SAMPLE_SIZE = int(os.getenv("TINYLFU_SAMPLE_SIZE", "10"))
ITEM_METADATA_CACHE_SIZE = 10000
CATEGORY_CACHE_SIZE = 50000
SEMANTIC_TTL_CACHE_SIZE = 500
ITEM_CLUSTER_CACHE_SIZE = 50000
LOG_FILE = "/app/data/log_15M_subset.txt"
LOG_DELIMITER = chr(1)
FILE_ENCODING = "latin-1"
VOLATILITY_HIGH = float(os.getenv("VOLATILITY_HIGH", "0.5"))
VOLATILITY_LOW = float(os.getenv("VOLATILITY_LOW", "0.1"))

LOW_VOLATILITY_THRESHOLD = float(os.getenv("LOW_VOLATILITY_THRESHOLD", "0.15"))
OPPORTUNITY_LOSS_THRESHOLD = float(os.getenv("OPPORTUNITY_LOSS_THRESHOLD", "0.001"))
REQUIRED_CONSECUTIVE_SNAPSHOTS = int(os.getenv("REQUIRED_CONSECUTIVE_SNAPSHOTS", "2"))
MIN_STEPS_IN_STABLE_BUT_INEFFECTIVE = int(os.getenv("MIN_STEPS_IN_STABLE_BUT_INEFFECTIVE", "5"))

from enum import Enum

class CacheAdaptationState(str, Enum):
    NORMAL = "NORMAL"
    UNSTABLE = "UNSTABLE"
    RECOVERY = "RECOVERY"
    STABLE_BUT_INEFFECTIVE = "STABLE_BUT_INEFFECTIVE"
